import { lstatSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { type Config } from "./config.js";
import { canonical, fail } from "./protocol.js";
import { atomicText } from "./storage.js";

function entry(path: string) {
  try {
    return lstatSync(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

interface Plan {
  directory: string;
  path: string;
  content: string;
  exists: boolean;
  previous?: string;
}

function mcpContent(config: Config, cli: string, node: string) {
  // JSON strings are valid TOML basic strings for supported filesystem paths.
  return [
    "# Generated by codex2claude; project scope only, no credentials.",
    "[mcp_servers.codex2claude]",
    `command = ${JSON.stringify(node)}`,
    `args = ${JSON.stringify([cli, "mcp", "codex", "--project", config.root])}`,
    `cwd = ${JSON.stringify(config.root)}`,
    "enabled = true",
    "startup_timeout_sec = 15",
    "tool_timeout_sec = 35",
    "",
  ].join("\n");
}

function generatedMcp(config: Config, content: string) {
  try {
    const lines = content.split("\n");
    const node = JSON.parse(lines[2]!.replace(/^command = /, ""));
    const args = JSON.parse(lines[3]!.replace(/^args = /, ""));
    return (
      typeof node === "string" &&
      Array.isArray(args) &&
      typeof args[0] === "string" &&
      content === mcpContent(config, args[0], node)
    );
  } catch {
    return false;
  }
}

function planMcp(
  config: Config,
  cli: string,
  node = process.execPath,
  refresh = false,
): Plan {
  const directory = join(config.root, ".codex");
  const path = join(directory, "config.toml");
  const directoryEntry = entry(directory);
  if (directoryEntry && !directoryEntry.isDirectory())
    fail("unsafe_codex_config_directory");
  const content = mcpContent(config, cli, node);
  // Do not merge/copy arbitrary existing Codex configuration or secret values.
  const fileEntry = entry(path);
  let previous: string | undefined;
  if (fileEntry) {
    if (!fileEntry.isFile() || fileEntry.isSymbolicLink())
      fail("unsafe_codex_config_file");
    const existing = readFileSync(path, "utf8");
    if (existing !== content) {
      if (!refresh || !generatedMcp(config, existing))
        fail("existing_codex_config_conflict");
      previous = existing;
    }
  }
  return { directory, path, content, exists: !!fileEntry, previous };
}

function apply(plan: Plan) {
  if (!plan.exists || plan.previous !== undefined) {
    if (plan.previous !== undefined) {
      const st = entry(plan.path);
      if (
        !st?.isFile() ||
        st.isSymbolicLink() ||
        readFileSync(plan.path, "utf8") !== plan.previous
      )
        fail("codex_config_changed_during_prepare");
    }
    mkdirSync(plan.directory, { recursive: true });
    atomicText(plan.path, plan.content, plan.previous !== undefined);
  }
  return plan.path;
}

export function prepareProjectMcp(
  config: Config,
  cli: string,
  node = process.execPath,
  refresh = false,
) {
  return apply(planMcp(config, cli, node, refresh));
}

export function prepareCodex(
  config: Config,
  cli: string,
  directMcp = false,
  node = process.execPath,
  refresh = false,
) {
  const directory = join(config.root, ".agents/plugins");
  for (const parent of [join(config.root, ".agents"), directory]) {
    const st = entry(parent);
    if (st && !st.isDirectory()) fail("unsafe_marketplace_directory");
  }
  const path = join(directory, "marketplace.json");
  const catalog = {
    name: "codex2claude-dev",
    interface: { displayName: "codex2claude — локальна розробка" },
    plugins: [
      {
        name: "codex2claude",
        source: { source: "local", path: "./.codex2claude/plugin" },
        policy: { installation: "AVAILABLE", authentication: "ON_USE" },
        category: "Productivity",
      },
    ],
  };
  const st = entry(path);
  if (st) {
    if (!st.isFile() || st.isSymbolicLink()) fail("unsafe_marketplace_file");
    if (
      canonical(JSON.parse(readFileSync(path, "utf8"))) !== canonical(catalog)
    )
      fail("existing_marketplace_conflict");
  }
  // Preflight both targets before publishing either. New files are exclusive;
  // a concurrent writer or disk failure can still require manual reconciliation.
  const mcp = directMcp ? planMcp(config, cli, node, refresh) : undefined;
  return {
    marketplace: apply({
      directory,
      path,
      content: JSON.stringify(catalog),
      exists: !!st,
    }),
    project_mcp_config: mcp ? apply(mcp) : undefined,
  };
}
